In [1]:
cd ..

/home/zw/Documents/project/ad-contest

In [2]:
from utils.often_use import *

In [3]:
ad, position, train, user, app_cat, test, ua_ac, user_apps = import_origin()

/home/zw/Documents/project/ad-contest/raw_data/pre/

In [4]:
train = pd.read_csv('note_book_code/middle_file/train_pre_29.csv')

In [9]:
appcount_of_user = pd.read_csv('note_book_code/middle_file/appcount_of_user.csv')

creative_popu = pd.read_csv('note_book_code/middle_file/creative_popu.csv')

In [11]:
creative_popu

    Unnamed: 0  appID     0  user_count  popularity
0            0     14   191         NaN         NaN
1            1     25    10         NaN         NaN
2            2     68    15         NaN         NaN
3            3     75    11         NaN         NaN
4            4     83     6         NaN         NaN
5            5     84   103         NaN         NaN
6            6     88     4         NaN         NaN
7            7    100    64         NaN         NaN
8            8    105    25         NaN         NaN
9            9    109     8         NaN         NaN
10          10    113     3         NaN         NaN
11          11    116   142         NaN         NaN
12          12    123   713         NaN         NaN
13          13    127    57         NaN         NaN
14          14    137     3         NaN         NaN
15          15    146    43         NaN         NaN
16          16    150    34         NaN         NaN
17          17    160     3         NaN         NaN
18          18    195    53         NaN         NaN
19          19    198   135         NaN         NaN
20          20    205    62         NaN         NaN
21          21    206     4         NaN         NaN
22          22    218    77         NaN         NaN
23          23    229     9         NaN         NaN
24          24    262     2         NaN         NaN
25          25    271     2         NaN         NaN
26          26    278   199         NaN         NaN
27          27    283     7         NaN         NaN
28          28    284     6         NaN         NaN
29          29    286   514         NaN         NaN
30          30    293    32         NaN         NaN
31          31    304    11         NaN         NaN
32          32    319    38         NaN         NaN
33          33    327    10         NaN         NaN
34          34    328   239         NaN         NaN
35          35    336   116         NaN         NaN
36          36    350     4         NaN         NaN
37          37    356    84      8180.0         4.0
38          38    360   146    282777.0         6.0
39          39    383    35     69835.0         5.0
40          40    389  1400      6240.0         4.0
41          41    391   193     15958.0         4.0
42          42    419     1        15.0         1.0
43          43    420    93      1577.0         3.0
44          44    421   763       102.0         2.0
45          45    428    42       999.0         3.0
46          46    434   803       763.0         3.0
47          47    442     7         1.0         0.0
48          48    465    56      1879.0         3.0
49          49    472     4         NaN         NaN

In [12]:
creative_popu.columns

Index([u'Unnamed: 0', u'appID', u'0', u'user_count', u'popularity'], dtype='object')

In [13]:
creative_popu['popularity'].isnull()

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49     True
Name: popularity, dtype: bool

In [14]:
creative_popu_loss = creative_popu.loc[creative_popu['popularity'].isnull(),:]

In [18]:
creative_popu2 = creative_popu[['appID','user_count','popularity']]
creative_popu2

    appID  user_count  popularity
0      14         NaN         NaN
1      25         NaN         NaN
2      68         NaN         NaN
3      75         NaN         NaN
4      83         NaN         NaN
5      84         NaN         NaN
6      88         NaN         NaN
7     100         NaN         NaN
8     105         NaN         NaN
9     109         NaN         NaN
10    113         NaN         NaN
11    116         NaN         NaN
12    123         NaN         NaN
13    127         NaN         NaN
14    137         NaN         NaN
15    146         NaN         NaN
16    150         NaN         NaN
17    160         NaN         NaN
18    195         NaN         NaN
19    198         NaN         NaN
20    205         NaN         NaN
21    206         NaN         NaN
22    218         NaN         NaN
23    229         NaN         NaN
24    262         NaN         NaN
25    271         NaN         NaN
26    278         NaN         NaN
27    283         NaN         NaN
28    284         NaN         NaN
29    286         NaN         NaN
30    293         NaN         NaN
31    304         NaN         NaN
32    319         NaN         NaN
33    327         NaN         NaN
34    328         NaN         NaN
35    336         NaN         NaN
36    350         NaN         NaN
37    356      8180.0         4.0
38    360    282777.0         6.0
39    383     69835.0         5.0
40    389      6240.0         4.0
41    391     15958.0         4.0
42    419        15.0         1.0
43    420      1577.0         3.0
44    421       102.0         2.0
45    428       999.0         3.0
46    434       763.0         3.0
47    442         1.0         0.0
48    465      1879.0         3.0
49    472         NaN         NaN

In [21]:
ad2 = pd.merge(ad,creative_popu2,how = 'left',on='appID')

In [22]:
ad2

,creativeID,adID,camgaignID,advertiserID,appID,appPlatform,user_count,popularity
0,4079,2318,147,80,14,2,NaN,NaN
1,4565,3593,632,3,465,1,1879.0,3.0
2,3170,1593,205,54,389,1,6240.0,4.0
3,6566,2390,205,54,389,1,6240.0,4.0
4,5187,411,564,3,465,1,1879.0,3.0
5,6440,3379,411,3,465,1,1879.0,3.0
6,2367,364,139,10,434,1,763.0,3.0
7,4686,834,107,80,14,2,NaN,NaN
8,2553,2519,60,3,465,1,1879.0,3.0
9,5832,100,73,54,389,1,6240.0,4.0
10,2392,2249,205,54,389,1,6240.0,4.0
11,5942,3598,693,26,123,2,NaN,NaN
12,5949,3084,566,80,14,2,NaN,NaN
13,1273,3170,56,26,123,2,NaN,NaN
14,3981,2924,513,44,421,1,102.0,2.0
15,4008,1063,365,80,14,2,NaN,NaN
16,6377,3242,375,80,14,2,NaN,NaN
17,2438,147,460,3,465,1,1879.0,3.0
18,697,1997,260,20,328,2,NaN,NaN
19,5184,167,310,36,123,2,NaN,NaN
20,1994,2812,412,20,328,2,NaN,NaN
21,2989,3513,477,80,14,2,NaN,NaN
22,6522,2361,625,57,421,1,102.0,2.0
23,3321,3561,106,22,218,2,NaN,NaN
24,750,750,141,87,116,2,NaN,NaN
25,2280,2519,60,3,465,1,1879.0,3.0
26,4862,822,205,54,389,1,6240.0,4.0
27,1004,411,564,3,465,1,1879.0,3.0
28,3307,17,216,80,14,2,NaN,NaN
29,5458,1120,310,36,123,2,NaN,NaN
...,...,...,...,...,...,...,...,...
6552,5117,305,56,26,123,2,NaN,NaN
6553,2943,3521,654,54,389,1,6240.0,4.0
6554,5657,306,139,10,434,1,763.0,3.0
6555,6498,3591,394,23,105,2,NaN,NaN
6556,1475,1059,56,26,123,2,NaN,NaN
6557,3581,2092,654,54,389,1,6240.0,4.0
6558,5035,3534,56,26,123,2,NaN,NaN
6559,3410,2766,176,29,218,2,NaN,NaN
6560,2477,3170,56,26,123,2,NaN,NaN
6561,2751,1100,413,44,421,1,102.0,2.0
6562,5098,2358,89,29,286,2,NaN,NaN
6563,2268,3006,654,54,389,1,6240.0,4.0
6564,4295,1650,569,54,389,1,6240.0,4.0
6565,2735,2653,654,54,389,1,6240.0,4.0
6566,1017,2017,647,56,123,2,NaN,NaN
6567,5513,2115,647,56,123,2,NaN,NaN
6568,69,955,56,26,123,2,NaN,NaN
6569,852,1122,647,56,123,2,NaN,NaN
6570,5514,765,58,57,421,1,102.0,2.0
6571,5351,2020,139,10,434,1,763.0,3.0
6572,1873,104,654,54,389,1,6240.0,4.0
6573,5997,925,139,10,434,1,763.0,3.0
6574,791,2709,662,60,68,2,NaN,NaN
6575,4645,1084,654,54,389,1,6240.0,4.0
6576,2451,2127,303,29,286,2,NaN,NaN
6577,5816,2634,615,26,123,2,NaN,NaN
6578,3860,1697,58,57,421,1,102.0,2.0
6579,1459,2445,112,54,389,1,6240.0,4.0
6580,2010,169,654,54,389,1,6240.0,4.0
6581,663,1685,394,23,105,2,NaN,NaN

In [27]:
train = pd.merge(train,ad2,how = 'left',on='creativeID')

In [28]:
train

,Unnamed: 0,label,clickTime,conversionTime,creativeID,userID,positionID,connectionType,telecomsOperator,adID,camgaignID,advertiserID,appID,appPlatform,user_count,popularity
0,0,0,170000,NaN,3089,2798058,293,1,1,1321,83,10,434,1,763.0,3.0
1,1,0,170000,NaN,1259,463234,6161,1,2,1535,685,80,14,2,NaN,NaN
2,2,0,170000,NaN,4465,1857485,7434,4,1,147,460,3,465,1,1879.0,3.0
3,3,0,170000,NaN,1004,2038823,977,1,1,411,564,3,465,1,1879.0,3.0
4,4,0,170000,NaN,1887,2015141,3688,1,1,369,144,84,360,1,282777.0,6.0
5,5,0,170000,NaN,3293,1177829,3347,1,1,2891,685,80,14,2,NaN,NaN
6,6,0,170000,NaN,4793,1257450,1876,1,2,1225,484,80,14,2,NaN,NaN
7,7,0,170000,NaN,1456,764204,6086,1,3,3379,411,3,465,1,1879.0,3.0
8,8,0,170000,NaN,4465,1438585,2426,2,3,147,460,3,465,1,1879.0,3.0
9,9,0,170000,NaN,985,1750317,5414,1,3,86,503,3,465,1,1879.0,3.0
10,10,0,170000,NaN,3465,2079582,6086,1,3,86,503,3,465,1,1879.0,3.0
11,11,0,170000,NaN,2764,2551467,977,1,1,147,460,3,465,1,1879.0,3.0
12,12,0,170000,NaN,997,2120928,5648,1,3,2982,661,80,14,2,NaN,NaN
13,13,0,170000,NaN,997,2292736,3498,1,1,2982,661,80,14,2,NaN,NaN
14,14,0,170000,NaN,4465,1119329,4635,3,3,147,460,3,465,1,1879.0,3.0
15,15,0,170000,NaN,3465,2256911,5013,1,1,86,503,3,465,1,1879.0,3.0
16,16,0,170000,NaN,3846,554021,932,1,1,493,379,84,360,1,282777.0,6.0
17,17,0,170000,NaN,6490,1666508,5347,1,1,1469,535,80,14,2,NaN,NaN
18,18,0,170000,NaN,5187,1082944,6850,2,3,411,564,3,465,1,1879.0,3.0
19,19,0,170000,NaN,1456,2437627,6086,1,3,3379,411,3,465,1,1879.0,3.0
20,20,0,170000,NaN,4686,1658851,1613,1,1,834,107,80,14,2,NaN,NaN
21,21,0,170000,NaN,4250,2009709,2831,1,1,1638,440,3,465,1,1879.0,3.0
22,22,0,170000,NaN,4465,1746056,4113,1,2,147,460,3,465,1,1879.0,3.0
23,23,0,170000,NaN,3575,1111108,6905,1,3,2757,70,80,14,2,NaN,NaN
24,24,0,170000,NaN,3531,402769,3347,1,1,2581,300,80,14,2,NaN,NaN
25,25,0,170000,NaN,5187,2428743,6086,1,1,411,564,3,465,1,1879.0,3.0
26,26,0,170000,NaN,3465,90746,2931,1,1,86,503,3,465,1,1879.0,3.0
27,27,0,170000,NaN,2137,217320,2579,1,1,2148,179,84,360,1,282777.0,6.0
28,28,0,170000,NaN,4250,1443907,6193,1,1,1638,440,3,465,1,1879.0,3.0
29,29,0,170000,NaN,726,912898,2150,1,1,1791,497,15,383,1,69835.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3113332,3113332,0,282359,NaN,1456,361690,6772,1,1,3379,411,3,465,1,1879.0,3.0
3113333,3113333,0,282359,NaN,5610,2119514,249,1,2,411,564,3,465,1,1879.0,3.0
3113334,3113334,0,282359,NaN,1004,2766816,977,2,3,411,564,3,465,1,1879.0,3.0
3113335,3113335,0,282359,NaN,4565,2515408,7197,1,2,3593,632,3,465,1,1879.0,3.0
3113336,3113336,0,282359,NaN,376,1123842,2579,1,1,3102,649,84,360,1,282777.0,6.0
3113337,3113337,0,282359,NaN,3012,585710,4818,1,2,1576,139,10,434,1,763.0,3.0
3113338,3113338,0,282359,NaN,4250,1292804,1530,1,1,1638,440,3,465,1,1879.0,3.0
3113339,3113339,1,282359,301033.0,1887,1012568,1245,1,1,369,144,84,360,1,282777.0,6.0
3113340,3113340,0,282359,NaN,3465,1583203,5024,1,1,86,503,3,465,1,1879.0,3.0
3113341,3113341,0,282359,NaN,410,780027,7149,1,1,2477,217,44,421,1,102.0,2.0
3113342,3113342,0,282359,NaN,3093,1575499,2692,2,1,86,503,3,465,1,1879.0,3.0
3113343,3113343,0,282359,NaN,2553,2477457,3688,1,2,2519,60,3,465,1,1879.0,3.0
3113344,3113344,0,282359,NaN,2553,168331,7366,1,1,2519,60,3,465,1,1879.0,3.0
3113345,3113345,0,282359,NaN,3586,55185,4867,2,1,2238,637,3,465,1,1879.0,3.0
3113346,3113346,0,282359,NaN,5209,240597,2579,1,2,293,82,84,360,1,282777.0,6.0
3113347,3113347,0,282359,NaN,5588,284474,2150,1,1,1502,23,15,383,1,69835.0,5.0
3113348,3113348,0,282359,NaN,5209,240597,2579,1,2,293,82,84,360,1,282777.0,6.0
3113349,3113349,0,282359,NaN,2764,1731672,7350,1,1,147,460,3,465,1,1879.0,3.0
3113350,3113350,0,282359,NaN,985,2612385,4867,1,1,86,503,3,465,1,1879.0,3.0
3113351,3113351,0,282359,NaN,4565,2072371,7262,1,1,3593,632,3,465,1,1879.0,3.0
3113352,3113352,0,282359,NaN,2982,1460744,3365,1,1,3379,411,3,465,1,1879.0,3.0
3113353,3113353,0,282359,NaN,4565,179405,2599,1,1,3593,632,3,465,1,1879.0,3.0
3113354,3113354,0,282359,NaN,4565,67345,5971,3,1,3593,632,3,465,1,1879.0,3.0
3113355,3113355,0,282359,NaN,6440,966364,846,1,2,3379,411,3,465,1,1879.0,3.0
3113356,3113356,0,282359,NaN,985,2031728,1465,2,3,86,503,3,465,1,1879.0,3.0
3113357,3113357,0,282359,NaN,863,2087582,1923,1,1,2238,637,3,465,1,1879.0,3.0
3113358,3113358,0,282359,NaN,4565,1442773,2891,1,3,3593,632,3,465,1,1879.0,3.0
3113359,3113359,0,282359,NaN,4432,317835,4455,1,1,1161,45,3,465,1,1879.0,3.0
3113360,3113360,0,282359,NaN,1456,829587,3232,1,3,3379,411,3,465,1,1879.0,3.0
3113361,3113361,0,282359,NaN,866,119946,3322,1,2,619,89,29,286,2,NaN,NaN

In [31]:
appcount_of_user = appcount_of_user[['userID','appcount','love_app']]

In [32]:
appcount_of_user

          userID  appcount  love_app
0           2838       505         4
1        1528113       480         4
2        1833356       465         4
3         615270       445         4
4        1849498       445         4
5        2121040       433         4
6         281637       428         4
7         403929       426         4
8        1679435       426         4
9        2379067       414         4
10       1914385       412         4
11        845201       411         4
12       1461702       406         4
13        373403       405         4
14       2648363       405         4
15       1700502       401         4
16       1906419       400         4
17        562051       395         4
18        291838       392         4
19        215857       390         4
20       1686079       389         4
21        305463       389         4
22        604933       386         4
23       2169166       386         4
24        174899       385         4
25       2085366       385         4
26       1018751       384         4
27       1346587       384         4
28       2769584       383         4
29        674047       383         4
...          ...       ...       ...
1446075  2592205         1         1
1446076   639734         1         1
1446077  1196645         1         1
1446078  1085477         1         1
1446079  1566266         1         1
1446080    32123         1         1
1446081  2592105         1         1
1446082   886991         1         1
1446083    82067         1         1
1446084  2591997         1         1
1446085  1566207         1         1
1446086  1962696         1         1
1446087  2325771         1         1
1446088  2592276         1         1
1446089  1060725         1         1
1446090  1154016         1         1
1446091  2446677         1         1
1446092   141436         1         1
1446093  1889403         1         1
1446094  1775403         1         1
1446095  1163701         1         1
1446096  1412310         1         1
1446097  2157696         1         1
1446098  1481407         1         1
1446099   802047         1         1
1446100  2241787         1         1
1446101   321159         1         1
1446102   529273         1         1
1446103  2325492         1         1
1446104   763044         1         1

[1446105 rows x 3 columns]

In [34]:
user = pd.merge(user,appcount_of_user,how='left',on='userID')

In [35]:
user

,userID,age,gender,education,marriageStatus,haveBaby,hometown,residence,appcount,love_app
0,1,42,1,0,2,0,512,503,79.0,4.0
1,2,18,1,5,1,0,1403,1403,NaN,NaN
2,3,0,2,4,0,0,0,0,NaN,NaN
3,4,21,2,5,3,0,607,607,NaN,NaN
4,5,22,2,0,0,0,0,1301,NaN,NaN
5,6,20,2,0,0,0,301,2301,NaN,NaN
6,7,17,1,5,0,0,313,313,NaN,NaN
7,8,21,1,2,3,1,1607,1607,NaN,NaN
8,9,38,2,2,2,0,2203,2203,3.0,1.0
9,10,13,2,0,0,0,0,2203,97.0,4.0
10,11,17,2,3,2,1,2405,1601,NaN,NaN
11,12,15,2,1,0,0,116,2101,38.0,1.0
12,13,20,1,0,0,0,604,601,NaN,NaN
13,14,0,0,0,0,0,0,602,62.0,3.0
14,15,0,0,0,0,0,0,513,NaN,NaN
15,16,19,1,1,0,0,510,1802,60.0,3.0
16,17,19,1,3,1,0,1403,1403,90.0,4.0
17,18,22,2,1,1,0,206,0,NaN,NaN
18,19,28,1,2,1,0,1011,1106,NaN,NaN
19,20,47,1,3,2,0,203,1008,106.0,4.0
20,21,14,0,0,0,0,0,104,49.0,2.0
21,22,15,1,2,0,0,0,2404,35.0,1.0
22,23,16,1,0,0,0,0,901,NaN,NaN
23,24,20,1,2,0,0,403,212,62.0,3.0
24,25,12,2,0,3,0,1003,1003,124.0,4.0
25,26,15,2,2,0,0,805,805,53.0,2.0
26,27,34,2,0,0,1,0,0,98.0,4.0
27,28,19,1,2,3,0,708,503,4.0,1.0
28,29,18,1,1,0,0,309,309,NaN,NaN
29,30,0,0,0,0,0,0,218,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2805088,2805089,22,1,2,3,0,302,302,76.0,4.0
2805089,2805090,18,1,1,0,0,2516,2516,41.0,2.0
2805090,2805091,31,1,0,2,0,0,0,NaN,NaN
2805091,2805092,10,2,4,1,0,1504,1504,NaN,NaN
2805092,2805093,28,2,1,0,1,603,2407,NaN,NaN
2805093,2805094,35,2,0,2,1,0,1501,89.0,4.0
2805094,2805095,27,2,0,1,0,0,1602,53.0,2.0
2805095,2805096,0,1,4,0,0,0,909,NaN,NaN
2805096,2805097,28,2,3,2,1,306,306,NaN,NaN
2805097,2805098,15,1,0,2,0,512,509,NaN,NaN
2805098,2805099,21,1,6,1,0,606,601,95.0,4.0
2805099,2805100,24,1,1,1,0,3001,3001,87.0,4.0
2805100,2805101,19,1,1,0,0,805,604,47.0,2.0
2805101,2805102,0,2,0,0,0,0,2109,NaN,NaN
2805102,2805103,50,1,1,2,0,1306,1208,125.0,4.0
2805103,2805104,36,1,2,2,0,0,2301,50.0,2.0
2805104,2805105,26,1,1,0,0,911,911,37.0,1.0
2805105,2805106,15,2,1,1,0,1901,1901,NaN,NaN
2805106,2805107,13,1,5,1,0,0,1901,31.0,1.0
2805107,2805108,26,2,0,1,0,2113,2113,NaN,NaN
2805108,2805109,15,1,5,1,0,1601,1601,NaN,NaN
2805109,2805110,18,1,2,1,0,804,206,NaN,NaN
2805110,2805111,20,2,1,3,1,1504,1512,52.0,2.0
2805111,2805112,39,2,1,2,0,1101,1101,NaN,NaN
2805112,2805113,14,1,3,1,0,0,805,NaN,NaN
2805113,2805114,0,0,0,0,0,0,0,NaN,NaN
2805114,2805115,14,1,3,0,0,1901,1901,NaN,NaN
2805115,2805116,27,1,5,0,5,0,1901,NaN,NaN
2805116,2805117,34,2,1,2,1,1304,1101,58.0,3.0
2805117,2805118,51,1,0,0,0,0,2601,NaN,NaN

In [36]:
train

,Unnamed: 0,label,clickTime,conversionTime,creativeID,userID,positionID,connectionType,telecomsOperator,adID,camgaignID,advertiserID,appID,appPlatform,user_count,popularity
0,0,0,170000,NaN,3089,2798058,293,1,1,1321,83,10,434,1,763.0,3.0
1,1,0,170000,NaN,1259,463234,6161,1,2,1535,685,80,14,2,NaN,NaN
2,2,0,170000,NaN,4465,1857485,7434,4,1,147,460,3,465,1,1879.0,3.0
3,3,0,170000,NaN,1004,2038823,977,1,1,411,564,3,465,1,1879.0,3.0
4,4,0,170000,NaN,1887,2015141,3688,1,1,369,144,84,360,1,282777.0,6.0
5,5,0,170000,NaN,3293,1177829,3347,1,1,2891,685,80,14,2,NaN,NaN
6,6,0,170000,NaN,4793,1257450,1876,1,2,1225,484,80,14,2,NaN,NaN
7,7,0,170000,NaN,1456,764204,6086,1,3,3379,411,3,465,1,1879.0,3.0
8,8,0,170000,NaN,4465,1438585,2426,2,3,147,460,3,465,1,1879.0,3.0
9,9,0,170000,NaN,985,1750317,5414,1,3,86,503,3,465,1,1879.0,3.0
10,10,0,170000,NaN,3465,2079582,6086,1,3,86,503,3,465,1,1879.0,3.0
11,11,0,170000,NaN,2764,2551467,977,1,1,147,460,3,465,1,1879.0,3.0
12,12,0,170000,NaN,997,2120928,5648,1,3,2982,661,80,14,2,NaN,NaN
13,13,0,170000,NaN,997,2292736,3498,1,1,2982,661,80,14,2,NaN,NaN
14,14,0,170000,NaN,4465,1119329,4635,3,3,147,460,3,465,1,1879.0,3.0
15,15,0,170000,NaN,3465,2256911,5013,1,1,86,503,3,465,1,1879.0,3.0
16,16,0,170000,NaN,3846,554021,932,1,1,493,379,84,360,1,282777.0,6.0
17,17,0,170000,NaN,6490,1666508,5347,1,1,1469,535,80,14,2,NaN,NaN
18,18,0,170000,NaN,5187,1082944,6850,2,3,411,564,3,465,1,1879.0,3.0
19,19,0,170000,NaN,1456,2437627,6086,1,3,3379,411,3,465,1,1879.0,3.0
20,20,0,170000,NaN,4686,1658851,1613,1,1,834,107,80,14,2,NaN,NaN
21,21,0,170000,NaN,4250,2009709,2831,1,1,1638,440,3,465,1,1879.0,3.0
22,22,0,170000,NaN,4465,1746056,4113,1,2,147,460,3,465,1,1879.0,3.0
23,23,0,170000,NaN,3575,1111108,6905,1,3,2757,70,80,14,2,NaN,NaN
24,24,0,170000,NaN,3531,402769,3347,1,1,2581,300,80,14,2,NaN,NaN
25,25,0,170000,NaN,5187,2428743,6086,1,1,411,564,3,465,1,1879.0,3.0
26,26,0,170000,NaN,3465,90746,2931,1,1,86,503,3,465,1,1879.0,3.0
27,27,0,170000,NaN,2137,217320,2579,1,1,2148,179,84,360,1,282777.0,6.0
28,28,0,170000,NaN,4250,1443907,6193,1,1,1638,440,3,465,1,1879.0,3.0
29,29,0,170000,NaN,726,912898,2150,1,1,1791,497,15,383,1,69835.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3113332,3113332,0,282359,NaN,1456,361690,6772,1,1,3379,411,3,465,1,1879.0,3.0
3113333,3113333,0,282359,NaN,5610,2119514,249,1,2,411,564,3,465,1,1879.0,3.0
3113334,3113334,0,282359,NaN,1004,2766816,977,2,3,411,564,3,465,1,1879.0,3.0
3113335,3113335,0,282359,NaN,4565,2515408,7197,1,2,3593,632,3,465,1,1879.0,3.0
3113336,3113336,0,282359,NaN,376,1123842,2579,1,1,3102,649,84,360,1,282777.0,6.0
3113337,3113337,0,282359,NaN,3012,585710,4818,1,2,1576,139,10,434,1,763.0,3.0
3113338,3113338,0,282359,NaN,4250,1292804,1530,1,1,1638,440,3,465,1,1879.0,3.0
3113339,3113339,1,282359,301033.0,1887,1012568,1245,1,1,369,144,84,360,1,282777.0,6.0
3113340,3113340,0,282359,NaN,3465,1583203,5024,1,1,86,503,3,465,1,1879.0,3.0
3113341,3113341,0,282359,NaN,410,780027,7149,1,1,2477,217,44,421,1,102.0,2.0
3113342,3113342,0,282359,NaN,3093,1575499,2692,2,1,86,503,3,465,1,1879.0,3.0
3113343,3113343,0,282359,NaN,2553,2477457,3688,1,2,2519,60,3,465,1,1879.0,3.0
3113344,3113344,0,282359,NaN,2553,168331,7366,1,1,2519,60,3,465,1,1879.0,3.0
3113345,3113345,0,282359,NaN,3586,55185,4867,2,1,2238,637,3,465,1,1879.0,3.0
3113346,3113346,0,282359,NaN,5209,240597,2579,1,2,293,82,84,360,1,282777.0,6.0
3113347,3113347,0,282359,NaN,5588,284474,2150,1,1,1502,23,15,383,1,69835.0,5.0
3113348,3113348,0,282359,NaN,5209,240597,2579,1,2,293,82,84,360,1,282777.0,6.0
3113349,3113349,0,282359,NaN,2764,1731672,7350,1,1,147,460,3,465,1,1879.0,3.0
3113350,3113350,0,282359,NaN,985,2612385,4867,1,1,86,503,3,465,1,1879.0,3.0
3113351,3113351,0,282359,NaN,4565,2072371,7262,1,1,3593,632,3,465,1,1879.0,3.0
3113352,3113352,0,282359,NaN,2982,1460744,3365,1,1,3379,411,3,465,1,1879.0,3.0
3113353,3113353,0,282359,NaN,4565,179405,2599,1,1,3593,632,3,465,1,1879.0,3.0
3113354,3113354,0,282359,NaN,4565,67345,5971,3,1,3593,632,3,465,1,1879.0,3.0
3113355,3113355,0,282359,NaN,6440,966364,846,1,2,3379,411,3,465,1,1879.0,3.0
3113356,3113356,0,282359,NaN,985,2031728,1465,2,3,86,503,3,465,1,1879.0,3.0
3113357,3113357,0,282359,NaN,863,2087582,1923,1,1,2238,637,3,465,1,1879.0,3.0
3113358,3113358,0,282359,NaN,4565,1442773,2891,1,3,3593,632,3,465,1,1879.0,3.0
3113359,3113359,0,282359,NaN,4432,317835,4455,1,1,1161,45,3,465,1,1879.0,3.0
3113360,3113360,0,282359,NaN,1456,829587,3232,1,3,3379,411,3,465,1,1879.0,3.0
3113361,3113361,0,282359,NaN,866,119946,3322,1,2,619,89,29,286,2,NaN,NaN

In [37]:
train = pd.merge(train,user,how='left',on='userID')

In [38]:
train

,Unnamed: 0,label,clickTime,conversionTime,creativeID,userID,positionID,connectionType,telecomsOperator,adID,...,popularity,age,gender,education,marriageStatus,haveBaby,hometown,residence,appcount,love_app
0,0,0,170000,NaN,3089,2798058,293,1,1,1321,...,3.0,25,2,1,3,1,0,1301,44.0,2.0
1,1,0,170000,NaN,1259,463234,6161,1,2,1535,...,NaN,20,2,1,1,0,0,213,NaN,NaN
2,2,0,170000,NaN,4465,1857485,7434,4,1,147,...,3.0,16,1,1,0,0,0,1502,NaN,NaN
3,3,0,170000,NaN,1004,2038823,977,1,1,411,...,3.0,0,0,0,0,0,0,1001,69.0,3.0
4,4,0,170000,NaN,1887,2015141,3688,1,1,369,...,6.0,35,1,2,2,0,1001,1001,NaN,NaN
5,5,0,170000,NaN,3293,1177829,3347,1,1,2891,...,NaN,30,2,1,2,1,107,107,NaN,NaN
6,6,0,170000,NaN,4793,1257450,1876,1,2,1225,...,NaN,24,2,2,1,0,0,0,28.0,1.0
7,7,0,170000,NaN,1456,764204,6086,1,3,3379,...,3.0,15,2,3,0,0,308,308,78.0,4.0
8,8,0,170000,NaN,4465,1438585,2426,2,3,147,...,3.0,19,1,1,1,0,803,601,NaN,NaN
9,9,0,170000,NaN,985,1750317,5414,1,3,86,...,3.0,19,1,1,1,0,2102,2102,88.0,4.0
10,10,0,170000,NaN,3465,2079582,6086,1,3,86,...,3.0,19,1,0,2,1,0,0,57.0,3.0
11,11,0,170000,NaN,2764,2551467,977,1,1,147,...,3.0,8,2,0,2,1,0,0,48.0,2.0
12,12,0,170000,NaN,997,2120928,5648,1,3,2982,...,NaN,25,1,2,1,0,1402,1402,NaN,NaN
13,13,0,170000,NaN,997,2292736,3498,1,1,2982,...,NaN,21,2,1,2,1,201,201,NaN,NaN
14,14,0,170000,NaN,4465,1119329,4635,3,3,147,...,3.0,18,1,1,0,0,3104,3104,91.0,4.0
15,15,0,170000,NaN,3465,2256911,5013,1,1,86,...,3.0,38,2,1,2,1,0,0,NaN,NaN
16,16,0,170000,NaN,3846,554021,932,1,1,493,...,6.0,30,1,0,2,1,0,2701,NaN,NaN
17,17,0,170000,NaN,6490,1666508,5347,1,1,1469,...,NaN,23,2,1,0,1,203,0,28.0,1.0
18,18,0,170000,NaN,5187,1082944,6850,2,3,411,...,3.0,18,1,1,1,0,0,101,63.0,3.0
19,19,0,170000,NaN,1456,2437627,6086,1,3,3379,...,3.0,15,1,3,1,0,0,2407,32.0,1.0
20,20,0,170000,NaN,4686,1658851,1613,1,1,834,...,NaN,22,2,2,0,1,204,206,46.0,2.0
21,21,0,170000,NaN,4250,2009709,2831,1,1,1638,...,3.0,0,0,0,0,0,0,0,NaN,NaN
22,22,0,170000,NaN,4465,1746056,4113,1,2,147,...,3.0,0,0,3,0,0,0,1901,90.0,4.0
23,23,0,170000,NaN,3575,1111108,6905,1,3,2757,...,NaN,38,2,3,2,1,802,802,NaN,NaN
24,24,0,170000,NaN,3531,402769,3347,1,1,2581,...,NaN,28,2,1,0,1,807,0,NaN,NaN
25,25,0,170000,NaN,5187,2428743,6086,1,1,411,...,3.0,32,1,0,0,0,0,307,55.0,2.0
26,26,0,170000,NaN,3465,90746,2931,1,1,86,...,3.0,21,1,0,0,0,0,0,37.0,1.0
27,27,0,170000,NaN,2137,217320,2579,1,1,2148,...,6.0,17,1,3,0,0,1503,1501,73.0,3.0
28,28,0,170000,NaN,4250,1443907,6193,1,1,1638,...,3.0,0,0,0,0,0,0,604,76.0,4.0
29,29,0,170000,NaN,726,912898,2150,1,1,1791,...,5.0,18,1,3,0,0,1303,512,61.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3113332,3113332,0,282359,NaN,1456,361690,6772,1,1,3379,...,3.0,28,1,0,1,0,215,206,NaN,NaN
3113333,3113333,0,282359,NaN,5610,2119514,249,1,2,411,...,3.0,12,2,3,1,0,0,1009,NaN,NaN
3113334,3113334,0,282359,NaN,1004,2766816,977,2,3,411,...,3.0,20,1,2,1,0,2402,1705,125.0,4.0
3113335,3113335,0,282359,NaN,4565,2515408,7197,1,2,3593,...,3.0,69,2,1,0,0,0,206,43.0,2.0
3113336,3113336,0,282359,NaN,376,1123842,2579,1,1,3102,...,6.0,18,2,1,0,0,405,402,NaN,NaN
3113337,3113337,0,282359,NaN,3012,585710,4818,1,2,1576,...,3.0,14,1,3,0,0,0,1306,65.0,3.0
3113338,3113338,0,282359,NaN,4250,1292804,1530,1,1,1638,...,3.0,20,2,0,1,0,2401,2403,56.0,3.0
3113339,3113339,1,282359,301033.0,1887,1012568,1245,1,1,369,...,6.0,25,1,1,1,0,0,705,86.0,4.0
3113340,3113340,0,282359,NaN,3465,1583203,5024,1,1,86,...,3.0,9,2,4,0,0,201,0,47.0,2.0
3113341,3113341,0,282359,NaN,410,780027,7149,1,1,2477,...,2.0,21,1,1,1,0,914,914,NaN,NaN
3113342,3113342,0,282359,NaN,3093,1575499,2692,2,1,86,...,3.0,22,2,2,0,5,1503,1501,136.0,4.0
3113343,3113343,0,282359,NaN,2553,2477457,3688,1,2,2519,...,3.0,31,1,3,1,0,1204,1401,NaN,NaN
3113344,3113344,0,282359,NaN,2553,168331,7366,1,1,2519,...,3.0,13,2,3,0,4,1503,1503,NaN,NaN
3113345,3113345,0,282359,NaN,3586,55185,4867,2,1,2238,...,3.0,33,1,2,2,0,801,801,63.0,3.0
3113346,3113346,0,282359,NaN,5209,240597,2579,1,2,293,...,6.0,0,1,3,2,0,1204,1204,29.0,1.0
3113347,3113347,0,282359,NaN,5588,284474,2150,1,1,1502,...,5.0,37,2,2,2,1,304,304,61.0,3.0
3113348,3113348,0,282359,NaN,5209,240597,2579,1,2,293,...,6.0,0,1,3,2,0,1204,1204,29.0,1.0
3113349,3113349,0,282359,NaN,2764,1731672,7350,1,1,147,...,3.0,46,1,0,2,0,602,602,NaN,NaN
3113350,3113350,0,282359,NaN,985,2612385,4867,1,1,86,...,3.0,12,1,3,0,0,401,2511,50.0,2.0
3113351,3113351,0,282359,NaN,4565,2072371,7262,1,1,3593,...,3.0,33,2,2,0,0,804,0,NaN,NaN
3113352,3113352,0,282359,NaN,2982,1460744,3365,1,1,3379,...,3.0,11,1,0,2,0,0,101,86.0,4.0
3113353,3113353,0,282359,NaN,4565,179405,2599,1,1,3593,...,3.0,13,2,3,2,0,2406,2406,20.0,1.0
3113354,3113354,0,282359,NaN,4565,67345,5971,3,1,3593,...,3.0,29,2,0,0,0,1206,1109,NaN,NaN
3113355,3113355,0,282359,NaN,6440,966364,846,1,2,3379,...,3.0,31,2,1,0,0,2208,2301,NaN,NaN
3113356,3113356,0,282359,NaN,985,2031728,1465,2,3,86,...,3.0,28,2,5,2,1,1709,1709,69.0,3.0
3113357,3113357,0,282359,NaN,863,2087582,1923,1,1,2238,...,3.0,25,2,6,3,1,2102,2903,59.0,3.0
3113358,3113358,0,282359,NaN,4565,1442773,2891,1,3,3593,...,3.0,29,1,0,2,0,605,605,NaN,NaN
3113359,3113359,0,282359,NaN,4432,317835,4455,1,1,1161,...,3.0,29,1,1,2,0,1406,0,61.0,3.0
3113360,3113360,0,282359,NaN,1456,829587,3232,1,3,3379,...,3.0,0,0,1,3,0,0,1708,64.0,3.0
3113361,3113361,0,282359,NaN,866,119946,3322,1,2,619,...,NaN,27,1,1,1,0,2410,2410,41.0,2.0

In [39]:
train.to_csv('note_book_code/middle_file/train_full.csv')

In [44]:
test = pd.merge(test,ad2,how='left',on='creativeID')

In [45]:
test = pd.merge(test,user,how='left',on='userID')

In [46]:
test

,instanceID,label,clickTime,creativeID,userID,positionID,connectionType,telecomsOperator,adID,camgaignID,...,popularity,age,gender,education,marriageStatus,haveBaby,hometown,residence,appcount,love_app
0,1,-1,310000,3745,1164848,3451,1,3,1166,430,...,NaN,29,2,1,0,1,605,605,34.0,1.0
1,2,-1,310000,2284,2127247,1613,1,3,1388,325,...,NaN,23,2,6,1,0,2205,2301,NaN,NaN
2,3,-1,310000,1456,2769125,5510,2,1,3379,411,...,3.0,28,1,0,0,0,0,1502,74.0,4.0
3,4,-1,310000,4565,9762,4113,2,3,3593,632,...,3.0,23,1,3,3,0,2405,2407,NaN,NaN
4,5,-1,310000,49,2513636,3615,1,3,1469,535,...,NaN,9,2,4,0,0,307,307,NaN,NaN
5,6,-1,310000,3824,488035,3821,1,1,2792,252,...,4.0,18,1,2,0,0,0,209,NaN,NaN
6,7,-1,310000,863,225561,4188,1,3,2238,637,...,3.0,12,1,4,0,0,0,111,NaN,NaN
7,8,-1,310000,4469,1144620,4113,1,1,2853,138,...,4.0,42,2,0,0,0,0,1408,90.0,4.0
8,9,-1,310000,3745,1113275,3347,1,2,1166,430,...,NaN,23,2,3,0,1,510,504,66.0,3.0
9,10,-1,310000,4565,1361729,2426,2,2,3593,632,...,3.0,32,1,1,2,1,1201,1201,92.0,4.0
10,11,-1,310000,4250,1749379,4292,1,3,1638,440,...,3.0,0,0,0,0,0,0,602,NaN,NaN
11,12,-1,310000,1456,840178,6086,1,1,3379,411,...,3.0,0,0,0,0,1,0,0,46.0,2.0
12,13,-1,310000,51,1945411,977,4,2,1638,440,...,3.0,22,1,0,0,0,0,2506,82.0,4.0
13,14,-1,310000,4250,1789615,5875,1,2,1638,440,...,3.0,17,1,3,0,0,1002,1002,62.0,3.0
14,15,-1,310000,5588,340733,2150,1,1,1502,23,...,5.0,0,0,4,2,0,0,2301,89.0,4.0
15,16,-1,310000,6001,1884781,1385,1,3,1655,139,...,3.0,19,2,0,0,0,1303,1303,NaN,NaN
16,17,-1,310000,4432,596931,6667,1,3,1161,45,...,3.0,22,1,1,1,0,1402,1402,NaN,NaN
17,18,-1,310000,4967,931181,6539,1,1,1166,430,...,NaN,18,2,6,1,0,511,511,NaN,NaN
18,19,-1,310000,1704,2657412,2695,1,0,571,402,...,4.0,17,1,0,3,0,0,702,60.0,3.0
19,20,-1,310000,4565,1251533,7135,1,1,3593,632,...,3.0,10,2,0,0,0,0,1406,87.0,4.0
20,21,-1,310000,3690,1199429,6932,1,1,998,402,...,4.0,14,2,3,0,1,1705,1705,73.0,3.0
21,22,-1,310000,5527,2455848,3228,1,3,972,138,...,4.0,35,2,1,2,0,2601,0,NaN,NaN
22,23,-1,310000,4565,1956857,5971,1,1,3593,632,...,3.0,2,0,0,1,0,0,707,74.0,4.0
23,24,-1,310000,1831,1191158,2461,1,3,352,252,...,4.0,17,1,0,2,0,0,313,44.0,2.0
24,25,-1,310000,6190,2272417,1465,1,1,266,138,...,4.0,0,0,5,2,0,0,307,40.0,1.0
25,26,-1,310000,2189,390752,3789,1,1,377,138,...,4.0,17,1,3,0,1,1811,1811,55.0,2.0
26,27,-1,310000,594,1399698,6161,1,2,2837,534,...,NaN,29,2,1,2,1,114,1102,NaN,NaN
27,28,-1,310000,4250,2297337,6193,2,1,1638,440,...,3.0,22,1,2,2,1,215,206,53.0,2.0
28,29,-1,310000,1092,1423913,5510,1,3,831,562,...,3.0,22,1,2,0,0,109,109,NaN,NaN
29,30,-1,310000,4250,1206944,2426,2,1,1638,440,...,3.0,22,1,3,1,0,0,202,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338459,338460,-1,312359,2389,1060910,1625,1,2,2899,252,...,4.0,33,2,3,2,1,0,0,47.0,2.0
338460,338461,-1,312359,4565,569989,4292,1,1,3593,632,...,3.0,47,2,0,2,1,1803,1803,33.0,1.0
338461,338462,-1,312359,863,478252,5030,1,3,2238,637,...,3.0,28,1,1,2,0,604,609,NaN,NaN
338462,338463,-1,312359,3871,2493985,2044,1,1,2807,402,...,4.0,14,2,3,0,4,219,219,NaN,NaN
338463,338464,-1,312359,2474,1712009,4818,1,2,1655,139,...,3.0,20,1,2,1,0,1310,1310,82.0,4.0
338464,338465,-1,312359,4257,1422501,2150,1,1,1608,69,...,4.0,0,0,4,0,0,0,1003,69.0,3.0
338465,338466,-1,312359,3690,1238716,522,1,3,998,402,...,4.0,14,2,0,0,0,101,101,NaN,NaN
338466,338467,-1,312359,5187,2323692,5510,1,1,411,564,...,3.0,29,1,3,1,0,0,408,84.0,4.0
338467,338468,-1,312359,3192,1020405,3322,1,2,1124,237,...,NaN,20,1,1,1,0,901,901,83.0,4.0
338468,338469,-1,312359,4432,364120,4455,1,3,1161,45,...,3.0,27,2,0,0,0,0,0,97.0,4.0
338469,338470,-1,312359,863,666507,5013,1,1,2238,637,...,3.0,45,1,0,2,0,2301,2301,63.0,3.0
338470,338471,-1,312359,5497,1163363,2823,1,3,3090,217,...,2.0,19,1,3,1,0,406,1901,NaN,NaN
338471,338472,-1,312359,4785,2160374,3322,1,2,2871,613,...,NaN,20,1,2,0,0,409,401,NaN,NaN
338472,338473,-1,312359,1465,2452121,7619,1,2,3141,277,...,NaN,23,2,5,1,0,1404,1404,7.0,1.0
338473,338474,-1,312359,985,1257057,4867,1,1,86,503,...,3.0,14,2,3,0,0,1401,1012,5.0,1.0
338474,338475,-1,312359,1456,106972,4657,1,1,3379,411,...,3.0,31,1,0,2,0,1802,0,76.0,4.0
338475,338476,-1,312359,750,1893932,3322,1,2,750,141,...,NaN,24,1,2,3,0,1103,1103,NaN,NaN
338476,338477,-1,312359,5258,1670094,3347,2,3,2195,369,...,NaN,27,1,0,1,0,904,901,NaN,NaN
338477,338478,-1,312359,3869,399524,3789,1,1,696,183,...,3.0,2,1,0,0,0,0,909,41.0,2.0
338478,338479,-1,312359,4077,2611278,2579,1,1,2698,201,...,3.0,18,1,4,1,0,2101,305,48.0,2.0
338479,338480,-1,312359,853,53208,2579,1,1,993,26,...,5.0,15,1,3,0,2,908,1104,73.0,3.0
338480,338481,-1,312359,1092,585337,103,1,1,831,562,...,3.0,52,2,2,2,1,0,0,46.0,2.0
338481,338482,-1,312359,5943,610001,2868,1,1,1638,440,...,3.0,0,0,0,2,0,0,801,38.0,1.0
338482,338483,-1,312359,2553,772834,4250,1,1,2519,60,...,3.0,35,1,5,2,0,810,810,74.0,4.0
338483,338484,-1,312359,6496,1043859,4867,1,3,933,504,...,3.0,12,1,5,0,0,204,102,74.0,4.0
338484,338485,-1,312359,1456,365374,4455,2,1,3379,411,...,3.0,21,1,1,1,0,1011,1011,NaN,NaN
338485,338486,-1,312359,2962,2231643,4818,1,2,146,138,...,4.0,0,0,0,0,0,0,0,NaN,NaN
338486,338487,-1,312359,4785,1673380,3322,1,3,2871,613,...,NaN,23,1,2,1,0,108,503,53.0,2.0
338487,338488,-1,312359,4432,1303085,4501,0,1,1161,45,...,3.0,16,2,3,0,0,204,204,NaN,NaN
338488,338489,-1,312359,2982,490286,7149,2,1,3379,411,...,3.0,20,2,1,0,1,1002,1009,NaN,NaN

In [47]:
test.to_csv('note_book_code/middle_file/test_full.csv')

In [48]:
train_half = train.loc[train['love_app'].isnull() == True,:]

In [50]:
train1 = train_half.loc[train_half['popularity'].isnull() == True,:]

In [51]:
train1.to_csv('note_book_code/middle_file/train1.csv')

In [52]:
train1 = train_half.loc[train_half['popularity'].isnull() == False,:]

In [53]:
train1.to_csv('note_book_code/middle_file/train2.csv')

In [54]:
train_half = train.loc[train['love_app'].isnull() == False,:]

In [55]:
train1 = train_half.loc[train_half['popularity'].isnull() == True,:]

In [56]:
train1.to_csv('note_book_code/middle_file/train3.csv')

In [57]:
train1 = train_half.loc[train_half['popularity'].isnull() == False,:]

In [58]:
train1.to_csv('note_book_code/middle_file/train4.csv')

In [59]:
test

,instanceID,label,clickTime,creativeID,userID,positionID,connectionType,telecomsOperator,adID,camgaignID,...,popularity,age,gender,education,marriageStatus,haveBaby,hometown,residence,appcount,love_app
0,1,-1,310000,3745,1164848,3451,1,3,1166,430,...,NaN,29,2,1,0,1,605,605,34.0,1.0
1,2,-1,310000,2284,2127247,1613,1,3,1388,325,...,NaN,23,2,6,1,0,2205,2301,NaN,NaN
2,3,-1,310000,1456,2769125,5510,2,1,3379,411,...,3.0,28,1,0,0,0,0,1502,74.0,4.0
3,4,-1,310000,4565,9762,4113,2,3,3593,632,...,3.0,23,1,3,3,0,2405,2407,NaN,NaN
4,5,-1,310000,49,2513636,3615,1,3,1469,535,...,NaN,9,2,4,0,0,307,307,NaN,NaN
5,6,-1,310000,3824,488035,3821,1,1,2792,252,...,4.0,18,1,2,0,0,0,209,NaN,NaN
6,7,-1,310000,863,225561,4188,1,3,2238,637,...,3.0,12,1,4,0,0,0,111,NaN,NaN
7,8,-1,310000,4469,1144620,4113,1,1,2853,138,...,4.0,42,2,0,0,0,0,1408,90.0,4.0
8,9,-1,310000,3745,1113275,3347,1,2,1166,430,...,NaN,23,2,3,0,1,510,504,66.0,3.0
9,10,-1,310000,4565,1361729,2426,2,2,3593,632,...,3.0,32,1,1,2,1,1201,1201,92.0,4.0
10,11,-1,310000,4250,1749379,4292,1,3,1638,440,...,3.0,0,0,0,0,0,0,602,NaN,NaN
11,12,-1,310000,1456,840178,6086,1,1,3379,411,...,3.0,0,0,0,0,1,0,0,46.0,2.0
12,13,-1,310000,51,1945411,977,4,2,1638,440,...,3.0,22,1,0,0,0,0,2506,82.0,4.0
13,14,-1,310000,4250,1789615,5875,1,2,1638,440,...,3.0,17,1,3,0,0,1002,1002,62.0,3.0
14,15,-1,310000,5588,340733,2150,1,1,1502,23,...,5.0,0,0,4,2,0,0,2301,89.0,4.0
15,16,-1,310000,6001,1884781,1385,1,3,1655,139,...,3.0,19,2,0,0,0,1303,1303,NaN,NaN
16,17,-1,310000,4432,596931,6667,1,3,1161,45,...,3.0,22,1,1,1,0,1402,1402,NaN,NaN
17,18,-1,310000,4967,931181,6539,1,1,1166,430,...,NaN,18,2,6,1,0,511,511,NaN,NaN
18,19,-1,310000,1704,2657412,2695,1,0,571,402,...,4.0,17,1,0,3,0,0,702,60.0,3.0
19,20,-1,310000,4565,1251533,7135,1,1,3593,632,...,3.0,10,2,0,0,0,0,1406,87.0,4.0
20,21,-1,310000,3690,1199429,6932,1,1,998,402,...,4.0,14,2,3,0,1,1705,1705,73.0,3.0
21,22,-1,310000,5527,2455848,3228,1,3,972,138,...,4.0,35,2,1,2,0,2601,0,NaN,NaN
22,23,-1,310000,4565,1956857,5971,1,1,3593,632,...,3.0,2,0,0,1,0,0,707,74.0,4.0
23,24,-1,310000,1831,1191158,2461,1,3,352,252,...,4.0,17,1,0,2,0,0,313,44.0,2.0
24,25,-1,310000,6190,2272417,1465,1,1,266,138,...,4.0,0,0,5,2,0,0,307,40.0,1.0
25,26,-1,310000,2189,390752,3789,1,1,377,138,...,4.0,17,1,3,0,1,1811,1811,55.0,2.0
26,27,-1,310000,594,1399698,6161,1,2,2837,534,...,NaN,29,2,1,2,1,114,1102,NaN,NaN
27,28,-1,310000,4250,2297337,6193,2,1,1638,440,...,3.0,22,1,2,2,1,215,206,53.0,2.0
28,29,-1,310000,1092,1423913,5510,1,3,831,562,...,3.0,22,1,2,0,0,109,109,NaN,NaN
29,30,-1,310000,4250,1206944,2426,2,1,1638,440,...,3.0,22,1,3,1,0,0,202,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338459,338460,-1,312359,2389,1060910,1625,1,2,2899,252,...,4.0,33,2,3,2,1,0,0,47.0,2.0
338460,338461,-1,312359,4565,569989,4292,1,1,3593,632,...,3.0,47,2,0,2,1,1803,1803,33.0,1.0
338461,338462,-1,312359,863,478252,5030,1,3,2238,637,...,3.0,28,1,1,2,0,604,609,NaN,NaN
338462,338463,-1,312359,3871,2493985,2044,1,1,2807,402,...,4.0,14,2,3,0,4,219,219,NaN,NaN
338463,338464,-1,312359,2474,1712009,4818,1,2,1655,139,...,3.0,20,1,2,1,0,1310,1310,82.0,4.0
338464,338465,-1,312359,4257,1422501,2150,1,1,1608,69,...,4.0,0,0,4,0,0,0,1003,69.0,3.0
338465,338466,-1,312359,3690,1238716,522,1,3,998,402,...,4.0,14,2,0,0,0,101,101,NaN,NaN
338466,338467,-1,312359,5187,2323692,5510,1,1,411,564,...,3.0,29,1,3,1,0,0,408,84.0,4.0
338467,338468,-1,312359,3192,1020405,3322,1,2,1124,237,...,NaN,20,1,1,1,0,901,901,83.0,4.0
338468,338469,-1,312359,4432,364120,4455,1,3,1161,45,...,3.0,27,2,0,0,0,0,0,97.0,4.0
338469,338470,-1,312359,863,666507,5013,1,1,2238,637,...,3.0,45,1,0,2,0,2301,2301,63.0,3.0
338470,338471,-1,312359,5497,1163363,2823,1,3,3090,217,...,2.0,19,1,3,1,0,406,1901,NaN,NaN
338471,338472,-1,312359,4785,2160374,3322,1,2,2871,613,...,NaN,20,1,2,0,0,409,401,NaN,NaN
338472,338473,-1,312359,1465,2452121,7619,1,2,3141,277,...,NaN,23,2,5,1,0,1404,1404,7.0,1.0
338473,338474,-1,312359,985,1257057,4867,1,1,86,503,...,3.0,14,2,3,0,0,1401,1012,5.0,1.0
338474,338475,-1,312359,1456,106972,4657,1,1,3379,411,...,3.0,31,1,0,2,0,1802,0,76.0,4.0
338475,338476,-1,312359,750,1893932,3322,1,2,750,141,...,NaN,24,1,2,3,0,1103,1103,NaN,NaN
338476,338477,-1,312359,5258,1670094,3347,2,3,2195,369,...,NaN,27,1,0,1,0,904,901,NaN,NaN
338477,338478,-1,312359,3869,399524,3789,1,1,696,183,...,3.0,2,1,0,0,0,0,909,41.0,2.0
338478,338479,-1,312359,4077,2611278,2579,1,1,2698,201,...,3.0,18,1,4,1,0,2101,305,48.0,2.0
338479,338480,-1,312359,853,53208,2579,1,1,993,26,...,5.0,15,1,3,0,2,908,1104,73.0,3.0
338480,338481,-1,312359,1092,585337,103,1,1,831,562,...,3.0,52,2,2,2,1,0,0,46.0,2.0
338481,338482,-1,312359,5943,610001,2868,1,1,1638,440,...,3.0,0,0,0,2,0,0,801,38.0,1.0
338482,338483,-1,312359,2553,772834,4250,1,1,2519,60,...,3.0,35,1,5,2,0,810,810,74.0,4.0
338483,338484,-1,312359,6496,1043859,4867,1,3,933,504,...,3.0,12,1,5,0,0,204,102,74.0,4.0
338484,338485,-1,312359,1456,365374,4455,2,1,3379,411,...,3.0,21,1,1,1,0,1011,1011,NaN,NaN
338485,338486,-1,312359,2962,2231643,4818,1,2,146,138,...,4.0,0,0,0,0,0,0,0,NaN,NaN
338486,338487,-1,312359,4785,1673380,3322,1,3,2871,613,...,NaN,23,1,2,1,0,108,503,53.0,2.0
338487,338488,-1,312359,4432,1303085,4501,0,1,1161,45,...,3.0,16,2,3,0,0,204,204,NaN,NaN
338488,338489,-1,312359,2982,490286,7149,2,1,3379,411,...,3.0,20,2,1,0,1,1002,1009,NaN,NaN

In [60]:
test_half = test.loc[test['love_app'].isnull() == True,:]

In [61]:
test1 = test_half.loc[test_half['popularity'].isnull() == True, :]

In [62]:
test1.to_csv('note_book_code/middle_file/test1.csv')

In [63]:
test1 = test_half.loc[test_half['popularity'].isnull() == False, :]

In [64]:
test1.to_csv('note_book_code/middle_file/test2.csv')

In [66]:
test_half = test.loc[test['love_app'].isnull() == False,:]

In [67]:
test1 = test_half.loc[test_half['popularity'].isnull() == True, :]

In [68]:
test1.to_csv('note_book_code/middle_file/test3.csv')

In [69]:
test1 = test_half.loc[test_half['popularity'].isnull() == False, :]

In [70]:
test1.to_csv('note_book_code/middle_file/test4.csv')